### ISSUE TITLE
Semiotic Hierarchy does not render

### ISSUE THREAD

**Issue by wilsonchua** [demartsc/tableau-semiotic-hierarchy#24]
Hello, I love your visualization schemes. I did try it out. But with no success. 
I don't get any error message, just a blank white screen area. 
My Tableau Version is: 2020.4.4 64 bit Windows 10 OS 
Here are my steps:
![image](https://user-images.githubusercontent.com/14941
441/119094795-0f2bc000-ba44-11eb-8b7a-33515ccf69b6.png)
![image](https://user-images.githubusercontent.com/14941441/119094813-1652ce00-ba44-11eb-8cbc-24996494d7f1.png)
![image](https://user-images.githubusercontent.com/14941441/119094880-29fe3480-ba44-11eb-8c69-b6609af00c5a.png)

On the next two wizard steps, I just accept the defaults. 
this is what I get:
![image](https://user-images.githubusercontent.com/14941441/119094941-3d110480-ba44-11eb-8307-751aba075e80.png)

**Comment by PG408** [comment]
I have the same issuse

**Comment by demartsc** [comment]
Can you please confirm that you are following the required data structure documented in the readme file? For example, in your screen shot, I do not see a root node with a null parent. 

<ul style="box-sizing: border-box; padding-left: 2em; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 46); font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li style="box-sizing: border-box;">Select a sheet that is on your dashboard and contains you hierarchy data. Here is an example table of what is required for hierarchy data for this extension to work correctly.</li></ul>
Parent Node | Child Node | Some Value | Color By | Other Stuff(n)
-- | -- | -- | -- | --
null | rootNode | 100 | black | categoryValue
rootNode | child1 | 20 | blue | categoryValue2
rootNode | child2 | 20 | green | categoryValue1
child1 | child3 | 100 | blue | categoryValue2
child1 | child4 | 100 | blue | categoryValue2
child2 | child5 | 100 | green | categoryValue1


<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 46); font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong style="box-sizing: border-box; font-weight: 600;">Please take note:</strong><span>&nbsp;</span>that there must be one, and only one record which has a null parent (even if it is fake), this is the<span>&nbsp;</span><code style="box-sizing: border-box; font-family: SFMono-Regular, Consolas, &quot;Liberation Mono&quot;, Menlo, monospace; font-size: 13.6px; padding: 0.2em 0.4em; margin: 0px; background-color: var(--color-markdown-code-bg); border-radius: 6px;">root node</code><span>&nbsp;</span>of your hierarchy from which all things are made, if you do not provide a single root node (in the souce data sheet), the extension will crash.</p>

**Comment by Calantha21** [comment]
I am having the same issue today. I tried to follow the instructions in the Tableau extension and use the most basic settings and nothing renders.
My data is literally
Parent Node  Child Node
null    Company A
Company A Company B
Company A Company C
Company A Company D

**Comment by demartsc** [comment]
Hi @Calantha21 ! I was able to render the extension without issue using your data set. You can see the workbook here on Tableau Public for reference: https://public.tableau.com/views/SemioticSimpleExample/Dashboard1?:language=en-US&:display_count=n&:origin=viz_share_link

![image](https://user-images.githubusercontent.com/22157638/123039771-95bb2080-d3a7-11eb-9d45-9d8496016c23.png)

If you are still getting issues, please confirm which Version of Tableau you are using if you don't mind. Thanks!

**Comment by Calantha21** [comment]
Hi Chris,

Thanks for the quick reply. Your sheet one looks exactly like mine. I did some more troubleshooting and here's what I have so far. I tried suspending my laptop VPN (I thought the corporate firewall might be blocking) - no luck. 

I'm using the version of Semiotic Hierarchy that is provided by the Extension Gallery now in version 2021.1.2. I also re-installed 2020.2 to see if that fixed it and downloaded the trex file from the public website to see if that fixed it.

So far, I still just get a blank screen. I've attached the screen shots - this is in 2021.1.2.

<img width="484" alt="snagit3" src="https://user-images.githubusercontent.com/86316518/123083870-84493700-d3ee-11eb-8ab1-e47c2afe1ffe.png">
<img width="528" alt="snagit2" src="https://user-images.githubusercontent.com/86316518/123083859-814e4680-d3ee-11eb-8c87-8905181b1aa5.png">
<img width="543" alt="snagit1" src="https://user-images.githubusercontent.com/86316518/123083833-7b586580-d3ee-11eb-8773-1f4415b609d3.png">

**Comment by Calantha21** [comment]
Hi Chris, I'm doing some more digging on the issue - because I really need this to work. I went to tableau-tc18-extending-tableau and downloaded all of the trex files and the tableau workbook. When I open TC18 Extending Tableau Demos.twbx, the following things happen: Projections demo renders fully, Phones render fully, violin renders fully, hierarchy demo - the top window is blank.

![image003](https://user-images.githubusercontent.com/86316518/123092383-6a145680-d3f8-11eb-8960-c13432337086.jpg)

**Comment by Calantha21** [comment]
So...I tracked down the culprit...the "Null" was not actually null...it was the word "Null"
Everything seems to be working now. Sorry for all the bother.

**Comment by demartsc** [comment]
Aww yes! The null value cannot be the strong null… the data prep stuff in the extension was probably failing due to not being able to find the root parent. Glad you got it sorted!

**Comment by demartsc** [comment]
Closing this issue.
